### ISSUE TITLE
 plugin pagos con tarjeta credito

### ISSUE THREAD

**Issue by darasat** [briansalvattore/mercado_pago_flutter#2]
Hola Brian,

primero antes que nada , destaco el gran trabajo de integración de la API de mercado pago en flutter.

Ahora mismo estoy probando los métodos de la librería y no he podido crear un pago.

me sale el siguiente error:

/flutter (20755): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'int' is not a subtype of type 'String'
E/flutter (20755): #0      MercadoPago._response (package:mercado_pago/src/services.dart:45:56)
E/flutter (20755): <asynchronous suspension>
E/flutter (20755): #1      MercadoPago._post (package:mercado_pago/src/services.dart:66:12)
E/flutter (20755): <asynchronous suspension>
E/flutter (20755): #2      MercadoPago.createPayment (package:mercado_pago/src/services.dart:172:18)
E/flutter (20755): <asynchronous suspension>

Respuesta:
 {message: Invalid card_token_id, error: bad_request, status: 400, cause: [{code: 3003, description: Invalid card_token_id, data: null}]

Status Code:
400

Algún tip para resolverlo?

Es un error? o podemos decir que este comportamiento ocurre por estar en modo de pruebas?

Gracias por responder.

estoy dispuesto a colaborar en este proyecto

un cordial saludo.

dejo mis datos de contacto
darasat@gmail.com
www.stratosoft.co

**Comment by briansalvattore** [comment]
Hola Diego, disculpa por demorarme en responder.

Voy a revisarlo, te mantengo al tanto, y te escribo al correo. Muchas gracias por el interés!

**Comment by wuilmerj24** [comment]
Hola tambien tengo ese problema. Esta resuelto o como se puede resolver?

**Comment by GuilhermeVendramini** [comment]
Here the fix.

https://github.com/briansalvattore/mercado_pago_flutter/pull/3/commits/d1ac271009515442d2b4d95c58a3d716f9e01ad7

**Comment by GuilhermeVendramini** [comment]
jsonBody["cause"][0]["code"] is returning empty. To get the code status replace:

int errorCode = int.tryParse(jsonBody["cause"][0]["code"]) ?? 404;

to

int errorCode = jsonBody["status"] ?? 404;

**Comment by catapulta-app** [comment]
Hola! Luego de la solución de Guilherme, ejecuté el método _createPayment()_ y la consola únicamente imprime:

flutter: payment => {message: Invalid installments, error: bad_request, status: 400, cause: [{code: 4033, description: Invalid installments, data: null}]}

No he podido concretar ningún pago debido a lo de arriba.

¿Alguno encontró la solución?

**Comment by catapulta-startup-sas** [comment]
Hola! Trato de realizar un pago y me encuentro con este problema:

message: Card not found, error: bad_request, status: 400, cause: [{code: 2010, description: Card not found, data: null}]

Pienso que tiene algo que ver con la creación del tokenId de la tarjeta.

¿Alguna idea?

**Comment by briansalvattore** [comment]
Hola, Mercadopago cambio el tipo de respuesta a String.

Acabo de subir una actualización corrigiendo el error. Espero que sea de ayuda.

https://pub.dev/packages/mercado_pago
