### ISSUE TITLE
Unhandled Exception: type 'int' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by fapcruz** [briansalvattore/mercado_pago_flutter#6]
Dear Brain,
How are you doing?
I hope everything is fine with you.
I am trying to implement your mercadopago package but it is showing an error as attached, it could help me, I am new to Dart / Flutter and I am not able to identify the solution.
I thank your attention.
Best regards
Fernando
[erro1.txt](https://github.com/briansalvattore/mercado_pago_flutter/files/4360639/erro1.txt)
[api_mp.dart.txt](https://github.com/briansalvattore/mercado_pago_flutter/files/4360642/api_mp.dart.txt)

**Comment by briansalvattore** [comment]
Hi, Mercadopago changed the response type to String.

I just uploaded an update correcting the error. I hope it helps.

https://pub.dev/packages/mercado_pago
